### PR TITLE
Update angular to v15

### PR DESCRIPTION
**Pull request by parth-baudhanwala**

### CODE REVIEW

**Comment by parth-baudhanwala** [comment]
@CuppaLabs I have upgraded package to angular v15. Could you please review, merge & publish?

**Comment by CuppaLabs** [comment]
@parth-baudhanwala Please give a week time to release your changes. We have other PR merged and release version pending. Rest assured it will be merged and release to be compatible with v15.

**Comment by bdstr** [comment]
@CuppaLabs When can we expect new release you've mentioned?

**Comment by ahmedsamirbek** [comment]
@CuppaLabs kindly we need this update urgently , could you please give it priority

**Comment by tiagodresch** [comment]
@CuppaLabs kindly we need this update urgently , could you please give it priority

**Comment by tiagodresch** [comment]
@CuppaLabs we also would like to upgrade to v17 after v15 is approved

**Comment by tiagodresch** [comment]
@parth-baudhanwala  they asked you a week time, but it already took 2 months. May we go ahead?

**Comment by R180105** [comment]
Is there any update plan?

**Comment by ashishvijay03** [comment]
@CuppaLabs Would you kindly check this PR? This library has to be compatible with the Ivy engine as soon as possible.

**Comment by sujithmathewthomas** [comment]
@CuppaLabs Kindly do something ASAP!!!

**Review by Beni312 — APPROVED** [review]

**Comment by selangley-wa** [comment]
For those who are able to, consider migrating to use the Angular Material Select component that is maintained by the Angular Team:

Select Component - Angular Material Version 18
https://material.angular.io/components/select/overview#multiple-selection

Select Component - Angular Material version 14
https://v14.material.angular.io/components/select/overview#multiple-selection

**Comment by rohanahata** [comment]
I have tried contacting the author on LinkedIn. 
Screenshot 2024-07-17 at 12 28 32 PM

**Comment by CuppaLabs** [comment]
Please Use v7.0.0 for angular 15 support.

**Pull request closed without merging**
