### PR TITLE
Server side api search

### PR DESCRIPTION
**Pull request by nikhilrane1992**
- Added onSearchInput for api search	
- Added example for api search input
- Handled local search, leazy loading search, and api search

### CODE REVIEW

**Comment by nikhilrane1992** [comment]
Hey any update on this. I want to use this package in my project.

**Comment by Zheness** [comment]
Hello, any update for this PR ? This would be a great adding.
Thanks :)

**Comment by CuppaLabs** [comment]
This implementation is done through templatizing the search field so that you can have a direct scope with your controller. Advanced and custom search / search API is in pipeline for this weeks release. Some major changes related to search field would be in upcoming release. So cannot acept this PR as of now. However will keep it open . :) Happy coding

**Comment by CuppaLabs** [comment]
feature now available in v2.9.0. Refer to example at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/customSearchAPI

**Pull request closed without merging**
