### PR TITLE
Update to Angular 13 

### PR DESCRIPTION
**Pull request by hypnotoad08**

### CODE REVIEW

**Review by bentzibentz — APPROVED** [review]
Looks and works for me. This should be released soon to use this awesome library with > v16

**Review by yerraguntlaharish — APPROVED** [review]

**Review by parth-baudhanwala — APPROVED** [review]

**Comment by parth-baudhanwala** [comment]
@CuppaLabs Need your attention over here. Please merge this PR & release latest version asap.

**Comment by CuppaLabs** [comment]
@parth-baudhanwala  @bentzibentz Thank you for your contribution. Will check this out. We need to check on the backward compatibility and work on a proper version info so as not to effect previous users. Give us 1-2 days to resolve this.

@parth-baudhanwala  Can you please remove the changes in the docs folder.

**Comment by hypnotoad08** [comment]
@CuppaLabs any updates on this? I see you finally replied to others on my pr 2 weeks ago

**Comment by CuppaLabs** [comment]
Done. Will release a npm package in couple of days.

**Pull request merged**
