### PR TITLE
Remove all button fixed

### PR DESCRIPTION
**Pull request by ircheg**
Hey, 

At the moment there is a small issue #425 :
If user clicks on 'UnSelect All' everything works as expected. But when user clicks on 'x' button the control is not marked as touched and the list of selected items is not updated.

### CODE REVIEW

**Comment by ircheg** [comment]
@CuppaLabs please, review this PR

**Comment by fzs1994** [comment]
Why this simple but important fix is not merged yet?!

**Comment by vishnu-dev** [comment]
Is this released @CuppaLabs? I'm still facing the same problem with 4.6.3

**Comment by dalitsun** [comment]
@CuppaLabs Do you plan to release a new version?

**Comment by ircheg** [comment]
@CuppaLabs 
please, release  a new version 🙏

**Comment by sethupathiramalingam** [comment]
Hi Team, 
I have 10 filters each filter values have more than 9k dataset. while I'm trying to load in the same time facing issues. due to dom creation. please me on this issue. 

thanks in advance.

**Pull request merged**
